server:
  port: 8081

spring:
  application:
    name: worker-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:workerhr}
    username: ${DB_USER:worker}
    password: ${DB_PASSWORD:worker}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: false

logging:
  level:
    root: INFO
